### ISSUE TITLE
Form Data Structure

### ISSUE THREAD

**Issue by EdgSgroi** [MyFormworks/Formworks#10]
The FWForm is the form structure itself. It can be built from the data got from JSON in the form of attributes and FWCompontent #9 structs or directly created with that structures. This is the object passed to the RootViewContoller #4 to interpret and make the UI form.

**Comment by Galdineris** [comment]
After discussions with @VicFalcetta @csfar @EdgSgroi and @cassiaabarbosa , the general data structure of the form was defined as 

## Form
- Form Title*
- Components*

## Component
- Component Title*
- Component Subtitle
- Error Label*
- Component Type*
- isObrigatory*
- Fields*

## Field
- Placeholder -> for TextFields
- Opcões -> for Selects

**Comment by Galdineris** [comment]
Dependent on #18

**Comment by Galdineris** [comment]
Merged to master in #37
