### ISSUE TITLE
Create the format options and attributes of the UI Components

### ISSUE THREAD

**Issue by csfar** [MyFormworks/Formworks#12]
Copied from Issue #8:

`One thing that will be needed to help our teams would be to create a document that will tell us how the UIComponents would be constructed, what kind of attributes they would have in their structs/classes.
Also it would be helpful that we create a JSON example or mock-up using one UIComponent as example to set our struct and how the users of our framework should implement it.
Any kind of alterations to this issue or opinions about it would be welcome.`

Refer to Issue #8 for more information.

**Comment by EdgSgroi** [comment]
Assim como comentei na issue #8 vale a pena olhar para a issue sobre o Jazzy #14 e ver como elas se relacionam.

**Comment by csfar** [comment]
Closed in favor of #31 and #9
