### ISSUE TITLE
ViewModel for the main view controller

### ISSUE THREAD

**Issue by cassiaabarbosa** [MyFormworks/Formworks#13]
This class it will be responsible to manage the form data that it will be presented on RootViewController #4 .

**Comment by EdgSgroi** [comment]
Seria interessante se fosse explicado como o RootViewModel utilizaria os componentes FWForm e FWComponent.

**Comment by cassiaabarbosa** [comment]
A classe RootViewModel será responsável por conter os dados que servirão para determinar quais serão os componentes (FWComponents) presentes no formulário (FWForm).
