### ISSUE TITLE
Use Jazzy as a Action to create code documentation

### ISSUE THREAD

**Issue by EdgSgroi** [MyFormworks/Formworks#14]
The Jazzy framework, presented by Babo, is a great solution to document code in a quick way during the development while this documentations is automatically released in a static HTML page. Also is a good opportunity to learn how to make a single and consistent documentation.

Jazzy repo: https://github.com/realm/jazzy

This issue can only be resolved with the help of the following issue in SwiftPM Jazzy Docs: 
https://github.com/sersoft-gmbh/swifty-docs-action/issues/1

**Comment by csfar** [comment]
Eu adicionei  a label de `dev-task` mas acho que não faz sentido. Pensei em criar uma chama de `repo`, para coisas como arrumar o CI, adicionar SwiftLint e o Jazzy. O que você acha?

**Comment by csfar** [comment]
Eu acho o uso do Jazzy algo legal. Podemos ter dois tipos de documentação: o Jazzy, para o código, e os docs em site estático, para tutoriais e etc.

**Comment by Galdineris** [comment]
Jazzy is still not updating the documentation and needs maintenance.
