### ISSUE TITLE
Add SwiftLint to the project

### ISSUE THREAD

**Issue by csfar** [MyFormworks/Formworks#15]
In order to enforce a coding style, we need to add SwiftLint to our project. We should also make sure that it runs on our CI.
I don't know which labels to add to this Issue. I am thinking of creating a new one for this sort of work, called `repo`.

**Comment by EdgSgroi** [comment]
Talvez fosse melhor criar uma label mais genérica, algo como "tools" ou coisa parecida. Isso pois sugeri utilizar o Jazzy na issue #14 e também não havia nenhuma label que especificasse bem além da label "documentation".

**Comment by csfar** [comment]
Tools! Perfeito, vou adicionar essa label.

**Comment by cassiaabarbosa** [comment]
There is no way to add SwiftLint without a Swift Target. So, we must add SwiftLint on Continuous Integration.
