### ISSUE TITLE
Structs creation

### ISSUE THREAD

**Issue by cassiaabarbosa** [MyFormworks/Formworks#16]
There should be a class to create FWForm #10 . This class will be responsible for translate the JSON  file and create the structs, that is the components.

**Comment by EdgSgroi** [comment]
Da uma olhada na issue #9 e veja como ela se relaciona com essa issue. Talvez valha a pena unir as duas em uma ou diferenciá-las ainda mais.

**Comment by csfar** [comment]
Closed in favor of #10
