### ISSUE TITLE
Change CI to build an XCode project

### ISSUE THREAD

**Issue by Galdineris** [MyFormworks/Formworks#17]
When the CI runs checks on our repository, it's not able to import common frameworks like UIKit as this is a framework, not an app project. 
To fix this, @csfar suggested we changed our workflow so it created an Xcode project to run the tests on.
[Based on this resource](https://arjunnayini.com/2019-11-01-github-ci-swift-package/).

**Comment by csfar** [comment]
There is a bit more information [here.](https://developer.apple.com/documentation/xcode/creating_a_standalone_swift_package_with_xcode)
