### ISSUE TITLE
Decoding JSON

### ISSUE THREAD

**Issue by cassiaabarbosa** [MyFormworks/Formworks#18]
In order to have data to create the form's components, we must decoding a JSON file, which has what will be presenting as components.

**Comment by csfar** [comment]
Apenas para ficar claro, no momento atual do projeto não iremos realizar chamadas de API e etc, certo?

**Comment by EdgSgroi** [comment]
Sim, a intenção é deixar a critério do desenvolvedor se ele vai passar um JSON para o framework ou se vai lidar diretamente com nossas estrutura, deixando assim dois possíveis caminhos a serem seguidos.

**Comment by Galdineris** [comment]
Dependent on #10

**Comment by VicFalcetta** [comment]
Estou pensando na classe que vai instanciar o JSON para ser criado, e depois preciso de algumas sugestões de vocês para pensar em algumas coisas. O JSON em si nas structs em teoria está pronto para ser decodificado, só vou rever nos documentos o melhor jeito de quem vai o receber e de como o receber.
