### ISSUE TITLE
Sample Project using our framework

### ISSUE THREAD

**Issue by Galdineris** [MyFormworks/Formworks#27]
Having a sample project using the framework is necessary for us to be used as a simple demo of our framework.

**Comment by csfar** [comment]
@cassiaabarbosa @EdgSgroi please remember to push to master the sample project before making the release branch.

**Comment by EdgSgroi** [comment]
The sample project was created in the following link:
https://github.com/MyFormworks/FormworksExample

**Comment by EdgSgroi** [comment]
The sample project was created in the following link:
https://github.com/MyFormworks/FormworksExample
