### ISSUE TITLE
Formworks Style Guide

### ISSUE THREAD

**Issue by Galdineris** [MyFormworks/Formworks#28]
Our framework acts directly on the UI and as such needs a style guide detailing at least the current components and their variations.

**Comment by VicFalcetta** [comment]
The style guide is located on the documents branch. Here it is for a quicker way to view it:
![StyleGuideV1](https://user-images.githubusercontent.com/49411841/94962035-2ecda280-04cc-11eb-874e-c9edeba93b37.jpg)
