### ISSUE TITLE
Requirements for building a form

### ISSUE THREAD

**Issue by Galdineris** [MyFormworks/Formworks#31]
To create forms, some amount of information is necessary. 
Which information will we need.

**Comment by EdgSgroi** [comment]
You are referring about the attributes required to create a form in the code or in a conceptual approach?

**Comment by csfar** [comment]
We've discussed which properties are required in our JSON, both from a conceptual and a code point of view. I suggest @Galdineris add what we discussed here.

**Comment by Galdineris** [comment]
thanks for the heads up @csfar , I sent it to the wrong issue. Bellow the message:

After discussions with @VicFalcetta @csfar @EdgSgroi and @cassiaabarbosa , the general data structure of the form was defined as 

## Form
- Form Title*
- Components*

## Component
- Component Title*
- Component Subtitle
- Error Label*
- Component Type*
- isObrigatory*
- Fields*

## Field
- Placeholder -> for TextFields
- Opcões -> for Selects

**Comment by csfar** [comment]
> thanks for the heads up @csfar , I sent it to the wrong issue. Bellow the message:
> 
> After discussions with @VicFalcetta @csfar @EdgSgroi and @cassiaabarbosa , the general data structure of the form was defined as
> 
> ## Form
> * Form Title*
> * Components*
> 
> ## Component
> * Component Title*
> * Component Subtitle
> * Error Label*
> * Component Type*
> * isObrigatory*
> * Fields*
> 
> ## Field
> * Placeholder -> for TextFields
> * Opcões -> for Selects

I think we should change from `isObrigatory` to `required`.

**Comment by Galdineris** [comment]
Needs to be added to documentation.
