### ISSUE TITLE
Create a JSON file for text fixture

### ISSUE THREAD

**Issue by Galdineris** [MyFormworks/Formworks#52]
Our test suite currently instantiates a JSON into code for tests to use. To truly test our framework, we should use JSON file directly to assert the result.

**Comment by csfar** [comment]
Add the JSON stub response in a folder named Stub inside the test target.

**Comment by cassiaabarbosa** [comment]
We have to document our JSON file.

**Comment by Galdineris** [comment]
Already achieved in other changes.
