### ISSUE TITLE
Review design of the framework

### ISSUE THREAD

**Issue by VicFalcetta** [MyFormworks/Formworks#54]
As stated by the framework's team, there are some visual aspects that need to be reviewed:
- [x] New 'Required' indicator because the old one was too big
- [x] Our own color identity so it can't conflict or cause problems with dark mode
- [x] Decide if it should stay as a CollectionViewCell or move to a TableViewCell pattern.
- [x] Work on a visual confirmation that the input is ok
- [x] Error message or some feedback when trying to send a form that is not valid

This will be checked and updated as work is done and commented so people can show their opinions and propose changes as needed.

**Comment by VicFalcetta** [comment]
![Light_Dark (1)](https://user-images.githubusercontent.com/49411841/96291056-ee871d80-0fbd-11eb-9fc7-3bda26c0cda3.png)

As seen in the image above, shadows were removed due to a bug in code that still needs to be fixing. Also the color scheme was changed, providing both a light and dark mode for the frame work using colors closer to the system.
For the "Required" symbol, it was decided to use the SF Symbol asterisk.filled.

**Comment by VicFalcetta** [comment]
![FormWorksStyleGuide](https://user-images.githubusercontent.com/49411841/96299340-4af03a00-0fca-11eb-9181-35611698e956.jpg)
This is the new format for the style guide. It has a better explanation of the components and how it will be visually presented.

**Comment by VicFalcetta** [comment]
For the visual confirmation, adding a green checkmark seems a viable option.
![Frame 2](https://user-images.githubusercontent.com/49411841/96303079-3878ff00-0fd0-11eb-9e5d-652160ecc3e1.png)
It is a SF Symbol same as the asterisk for the "Required" designation. When the form is correct this check mark should replace the "Required" symbol.

**Comment by Galdineris** [comment]
Diluted into various PRs.
