### ISSUE TITLE
Generic Text Input Field Component

### ISSUE THREAD

**Issue by csfar** [MyFormworks/Formworks#6]
A simple single line text input component should be added to our framework. We are trying to avoid using TextField Component as the name of this component but we are having a hard time coming up with a new name.
This component should have a title for the field, the input field itself and a placeholder.
@VicFalcetta and I will be adding a low fidelity prototype to help in the process of building the component.

**Comment by csfar** [comment]
Here are a few images of the low fidelity prototype:

**Component**
![Generic Text Field Component](https://user-images.githubusercontent.com/28116556/94189870-b0488380-fe81-11ea-9ee4-2660a8ab9ad9.jpg)

**Spec**
![GTFC-Spec](https://user-images.githubusercontent.com/28116556/94189886-b5a5ce00-fe81-11ea-96d1-69bf6a8b1cbc.jpg)

**Example**
![GTFC-Spec-Group](https://user-images.githubusercontent.com/28116556/94189889-b8082800-fe81-11ea-8e33-fede0f7d9b0c.jpg)

**Comment by VicFalcetta** [comment]
For the moment this was only to imagine how it would like. One thing that I would like to ask is for suggestions for the visuals and how to separate each component. Comment on things such as font size and style, gap between then and if it should have "physical" separators like lines or be in boxes.

**Comment by VicFalcetta** [comment]
![Exemplo de alta fidelidade (1)](https://user-images.githubusercontent.com/49411841/94463557-851ca780-0193-11eb-9900-92d9ba0eac81.png)

Here it is a high-fidelity example that I made as I imagined it would be the One-Line text field for general purpose usage. It would be nice if you could provide some feedback on it, like what you would like to be changed.

**Comment by VicFalcetta** [comment]
Here are some variations that I made for the text box, including a secure version (that just adds a visual indication) and a multi-line text.

![Exemplo de alta fidelidade- One Line Text Alt 1](https://user-images.githubusercontent.com/49411841/94469242-21e34300-019c-11eb-9d42-d8254d288129.png)

![Exemplo de alta fidelidade- One Line Secure](https://user-images.githubusercontent.com/49411841/94469251-26a7f700-019c-11eb-9333-6f9b06062b47.png)

![Exemplo de alta fidelidade - Multi-Line Text](https://user-images.githubusercontent.com/49411841/94469258-2a3b7e00-019c-11eb-93ef-f23e52ea38ce.png)

There are some variations that other developers have suggested, such as an email and telephone box. As deemed necessary we will provide more details and examples here.

**Comment by VicFalcetta** [comment]
To get a better view on how it would be on the screen of iPhone, here's a medium prototype so you can see the application:

![High-fidelity Prot](https://user-images.githubusercontent.com/49411841/94469801-15abb580-019d-11eb-9791-9537f659e597.png)

**Comment by VicFalcetta** [comment]
As it was mentioned before and suggested by some of our members, here are some variations of the text field for email and phone number.

![Exemplo de alta fidelidade- Email field](https://user-images.githubusercontent.com/49411841/94477559-74c2f780-01a8-11eb-81a6-db8e8655a95a.png)

![Exemplo de alta fidelidade- Email field (1)](https://user-images.githubusercontent.com/49411841/94477572-7a204200-01a8-11eb-856b-2f26a26e7a75.png)

For convenience, please suggest any alternate versions or extra components **through the discussion thread on GitHub** so we have a more centralized discussion to aid the development.

**Comment by csfar** [comment]
We need to be careful with phone numbers since it changes quite a lot from place to place. We could look into how other frameworks/apps do phone verification. We may have to use an API for that, which is something we should discuss. Will we allow API calls from inside the framework for input validation?
I think the email one is great! 👏

**Comment by VicFalcetta** [comment]
Yeah, I agree with the fact of being hard to verify all types and formats of numbers. One solution that I had though after I read your comment it was to implement our Regex verifier for some formats and let the developer create his own regex verifier as an attribute for the field.

One more thing, as per request from one of our development team members and suggestion from one of PO was to create a use case for our framework. So, in order to satisfy it I created one in Portuguese (the dev can write in any language he wants the labels) when you order food and a problem happens. This is what I consider to be one High-fidelity prototype for our framework.
![CasoPedidoProblema (1)](https://user-images.githubusercontent.com/49411841/94481663-755e8c80-01ae-11eb-8749-9fd9884c69b6.png)

**Comment by Galdineris** [comment]
Thread locked by #13
