### ISSUE TITLE
Add FWFormConfiguration class responsible for initialization using JSON and a style

### ISSUE THREAD

**Issue by csfar** [MyFormworks/Formworks#67]
Implement new final class named `FWFormConfiguration` responsible for initializing the `FWFormViewController` and its `ViewModel` based off the JSON passed in the init. Also, make sure a style is one of the init parameters.

**Comment by cassiaabarbosa** [comment]
I have a doubt: what is style in our project?

**Comment by cassiaabarbosa** [comment]
The FWFormViewController should have viewModel variable yet?

**Comment by Galdineris** [comment]
@cassiaabarbosa https://github.com/Galdineris/Formworks/blob/documentation/formworks-structure/Resources/glossary.md
The style definition it's in the glossary we wrote together over on the documentation/formworks-structure branch

**Comment by cassiaabarbosa** [comment]
The only one form style is text style, it isn't?

**Comment by Galdineris** [comment]
Closed in PR #78
