### ISSUE TITLE
Document the format options and attributes of the UI Components

### ISSUE THREAD

**Issue by VicFalcetta** [MyFormworks/Formworks#8]
One thing that will be needed to help our teams would be to create a document that will tell us how the UIComponents would be constructed, what kind of attributes they would have in their structs/classes.
Also it would be helpful that we create a JSON example or mock-up using one UIComponent as example to set our struct and how the users of our framework should implement it.

Any kind of alterations to this issue or opinions about it would be welcome.

**Comment by EdgSgroi** [comment]
De uma olhada na issue #14 que fala de usar o Jazzy para documentação de código, se gostar da ideia e fizer sentido como uma solução mais específica para essa issue, discutimos sobre qual vale a pena manter.

**Comment by Galdineris** [comment]
Closed in favor of #31
