### ISSUE TITLE
Protocol for UI Components Data

### ISSUE THREAD

**Issue by EdgSgroi** [MyFormworks/Formworks#9]
FWComponent is the protocol implemented ideally by structs that will save data used to create UIComponents and data obtained on the form. This protocol can be implemented in case the user wants to create a custom struct.

**Comment by VicFalcetta** [comment]
Uma coisa que não ficou clara para mim. O FWComponent ser um único protocolo, e este será aplicado nas structs para poder criar os componentes na view? Isso é só para eu ter certeza para ter noção se eu entendi de forma correta.

**Comment by EdgSgroi** [comment]
Exatamente. A ideia é usar um protocolo pra dar a liberdade do usuário criar seus próprios componentes.

**Comment by Galdineris** [comment]
Closed in favor of #37
